{% set name = "warpx" %}
{% set version = "22.03" %}
{% set build = 0 %}
{% set sha256 = "ddbef760c8000f2f827dfb097ca3359e7aecbea8766bec5c3a91ee28d3641564" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ECP-WarpX/WarpX/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  run_exports:
    # releases are not (yet) compatible
    - warpx {{ version }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ccache        # [unix]
    - clang         # [win]
    - lld           # [win]
    # TODO: add libxml2 dep in lld-feedstock
    - libxml2       # [win]
    - make          # [unix]
    - ninja         # [win]
    - cmake >=3.18.0
    - libgomp       # [linux]
    - llvm-openmp   # [osx or win]
  host:
    - blaspp
    - boost-cpp
    - lapackpp
    - openpmd-api
    - pip
    - python
    - setuptools
    - wheel
    - fftw
    - pkgconfig
# ninja: error: 'D:/bld/warpx_1615224319242/_h_env/Library/lib/lapack.lib', needed by 'lib/warpx.RZ.NOMPI.OMP.DP.OPMD.PSATD.QED.dll', missing and no known rule to make it
    - liblapack   # [win]
    - liblapacke  # [win]
# ninja: error: 'D:/bld/warpx_1635938394765/_h_env/Library/lib/blas.lib', needed by 'lib/warpx.RZ.NOMPI.OMP.DP.OPMD.PSATD.QED.dll', missing and no known rule to make it
    - libblas   # [win]
    - libcblas  # [win]
  run:
    - numpy
    - periodictable
    - picmistandard ==0.0.19
    - python
    - scipy

test:
  source_files:
    - Examples/Physics_applications/laser_acceleration/inputs_*
    - Examples/Physics_applications/laser_acceleration/PICMI_inputs_*
  files:
    - test.sh   # [unix]
    - test.bat  # [win]
  imports:
    - pywarpx
  commands:
    - test -f ${PREFIX}/bin/warpx.1d.NOMPI.OMP.DP.OPMD.PSATD.QED  # [unix]
    - test -f ${PREFIX}/bin/warpx.2d.NOMPI.OMP.DP.OPMD.PSATD.QED  # [unix]
    - test -f ${PREFIX}/bin/warpx.3d.NOMPI.OMP.DP.OPMD.PSATD.QED  # [unix]
    - test -f ${PREFIX}/bin/warpx.RZ.NOMPI.OMP.DP.OPMD.PSATD.QED  # [unix]
    - if not exist %LIBRARY_PREFIX%\bin\warpx.1d.NOMPI.OMP.DP.OPMD.PSATD.QED.exe exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\bin\warpx.2d.NOMPI.OMP.DP.OPMD.PSATD.QED.exe exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\bin\warpx.3d.NOMPI.OMP.DP.OPMD.PSATD.QED.exe exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\bin\warpx.RZ.NOMPI.OMP.DP.OPMD.PSATD.QED.exe exit 1  # [win]
    # smoke tests: execute
    - ./test.sh      # [unix and build_platform == target_platform]
    - call test.bat  # [win]

about:
  home: https://ecp-warpx.github.io
  license: BSD-3-Clause-LBNL
  license_family: BSD
  license_file: LICENSE.txt
  summary: WarpX is an advanced electromagnetic Particle-In-Cell code.

  description: |
    WarpX is an advanced electromagnetic Particle-In-Cell code.
    It supports many features including: Perfectly-Matched Layers (PML),
    Boosted-frame simulations, particle collisions, mesh refinement.

  doc_url: https://warpx.readthedocs.io
  dev_url: https://github.com/ECP-WarpX/WarpX

extra:
  recipe-maintainers:
    - ax3l
    - RemiLehe
