{% set name = "warpx" %}
{% set version = "25.02" %}
{% set build = 0 %}
{% set sha256 = "c65385a3598bf43278c0b1c10ae2a5a07c1a46f6fa98deded385ecca2021a1a2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ECP-WarpX/WarpX/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  skip: true  # [python_impl == 'pypy']
  run_exports:
    # releases are not (yet) compatible
    - warpx {{ version }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - clang         # [win]
    - lld           # [win]
    - make          # [unix]
    - ninja         # [win]
    - pkg-config
    - cmake
    - libgomp       # [linux]
    - llvm-openmp   # [osx or win]
  host:
    - amrex >={{ version }}
    - blaspp
    - libboost-headers
    - lapackpp
    - numpy
    - openpmd-api=*=nompi*
    - pip
    - pyamrex >={{ version }}
    - pybind11
    - pybind11-abi
    - python
    - setuptools
    - wheel
    - fftw
# ninja: error: 'D:/bld/warpx_1615224319242/_h_env/Library/lib/lapack.lib', needed by 'lib/warpx.rz.NOMPI.OMP.DP.OPMD.FFT.QED.dll', missing and no known rule to make it
    - liblapack   # [win]
    - liblapacke  # [win]
# ninja: error: 'D:/bld/warpx_1635938394765/_h_env/Library/lib/blas.lib', needed by 'lib/warpx.rz.NOMPI.OMP.DP.OPMD.FFT.QED.dll', missing and no known rule to make it
    - libblas   # [win]
    - libcblas  # [win]
  run:
    - periodictable
    - picmistandard ==0.33.0
    - pyamrex >={{ version }}
    - python
    - scipy

test:
  source_files:
    - Examples/Physics_applications/laser_acceleration/inputs_*
  files:
    - test.sh   # [unix]
    - test.bat  # [win]
  imports:
    - pywarpx
  commands:
    - test -f ${PREFIX}/bin/warpx.1d.NOMPI.OMP.DP.PDP.OPMD.FFT.EB.QED  # [unix]
    - test -f ${PREFIX}/bin/warpx.2d.NOMPI.OMP.DP.PDP.OPMD.FFT.EB.QED  # [unix]
    - test -f ${PREFIX}/bin/warpx.3d.NOMPI.OMP.DP.PDP.OPMD.FFT.EB.QED  # [unix]
    - test -f ${PREFIX}/bin/warpx.rz.NOMPI.OMP.DP.PDP.OPMD.FFT.EB.QED  # [unix]
    - if not exist %LIBRARY_PREFIX%\bin\warpx.1d.NOMPI.OMP.DP.PDP.OPMD.FFT.EB.QED.exe exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\bin\warpx.2d.NOMPI.OMP.DP.PDP.OPMD.FFT.EB.QED.exe exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\bin\warpx.3d.NOMPI.OMP.DP.PDP.OPMD.FFT.EB.QED.exe exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\bin\warpx.rz.NOMPI.OMP.DP.PDP.OPMD.FFT.EB.QED.exe exit 1  # [win]
    # smoke tests: execute
    - ./test.sh      # [unix and build_platform == target_platform]
    - call test.bat  # [win]

about:
  home: https://ecp-warpx.github.io
  license: BSD-3-Clause-LBNL
  license_family: BSD
  license_file: LICENSE.txt
  summary: WarpX is an advanced electromagnetic Particle-In-Cell code.

  description: |
    WarpX is an advanced electromagnetic Particle-In-Cell code.
    It supports many features including: Perfectly-Matched Layers (PML),
    Boosted-frame simulations, particle collisions, mesh refinement.

  doc_url: https://warpx.readthedocs.io
  dev_url: https://github.com/ECP-WarpX/WarpX

extra:
  recipe-maintainers:
    - ax3l
    - EZoni
    - RemiLehe
