schema_version: 1

context:
  name: warpx
  version: "25.04"
  build: 0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/BLAST-WarpX/warpx/archive/${{ version }}.tar.gz
  sha256: 374136fbf566d65307dfe95ae12686ccaf3e649d2f66a79cd856585986c94ac7

build:
  skip: python_impl == "pypy" or (target_platform == "linux-aarch64" and python == "3.13.* *_cp313")
  number: ${{ build }}

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - pybind11
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - if: unix
      then: make
    - if: win
      then:
        - clang
        - lld
        - llvm-openmp
        - ninja
    - if: linux
      then: libgomp
    - if: osx
      then: llvm-openmp
    - cmake
    - pkg-config

  host:
    - amrex ==${{ version }}[build=nompi_*]
    - blaspp
    - libboost-headers
    - lapackpp
    - numpy
    - openpmd-api * [build=nompi_*]
    - pip
    - pyamrex ==${{ version }}[build=nompi_*]
    - pybind11
    - pybind11-abi
    - python
    - setuptools
    - wheel
    - fftw
    - if: win
      then:
# ninja: error: 'D:/bld/warpx_1615224319242/_h_env/Library/lib/lapack.lib', needed by 'lib/warpx.rz.NOMPI.OMP.DP.OPMD.FFT.QED.dll', missing and no known rule to make it
        - liblapack
        - liblapacke
# ninja: error: 'D:/bld/warpx_1635938394765/_h_env/Library/lib/blas.lib', needed by 'lib/warpx.rz.NOMPI.OMP.DP.OPMD.FFT.QED.dll', missing and no known rule to make it
        - libblas
        - libcblas
  run:
    - periodictable
    - picmistandard ==0.33.0
    - pyamrex ==${{ version }}[build=nompi_*]
    - python
    - scipy

  run_exports:
    # releases are not (yet) compatible
    - warpx ==${{ version }}

tests:
  - python:
      imports:
        - pywarpx
      pip_check: false
  - package_contents:
      files:
        - if: unix
          then:
            - bin/warpx.1d.NOMPI.OMP.DP.PDP.OPMD.FFT.EB.QED
            - bin/warpx.2d.NOMPI.OMP.DP.PDP.OPMD.FFT.EB.QED
            - bin/warpx.rz.NOMPI.OMP.DP.PDP.OPMD.FFT.EB.QED
            - bin/warpx.3d.NOMPI.OMP.DP.PDP.OPMD.FFT.EB.QED
        - if: win
          then:
            - Library/bin/warpx.1d.NOMPI.OMP.DP.PDP.OPMD.FFT.EB.QED.exe
            - Library/bin/warpx.2d.NOMPI.OMP.DP.PDP.OPMD.FFT.EB.QED.exe
            - Library/bin/warpx.rz.NOMPI.OMP.DP.PDP.OPMD.FFT.EB.QED.exe
            - Library/bin/warpx.3d.NOMPI.OMP.DP.PDP.OPMD.FFT.EB.QED.exe
  - script:
      - echo "Testing..."
      - if: unix and (build_platform == target_platform)
        then: ./test.sh
      - if: win
        then: call test.bat
    files:
      recipe:
        - if: unix
          then: test.sh
        - if: win
          then: test.bat
      source:
        - Examples/Physics_applications/laser_acceleration/inputs_*

about:
  license: BSD-3-Clause-LBNL
  license_file: LICENSE.txt
  summary: WarpX is an advanced electromagnetic & electrostatic Particle-In-Cell code.
  description: |
    WarpX is an advanced electromagnetic & electrostatic Particle-In-Cell code.
    It supports many features including: Perfectly-Matched Layers (PML),
    Boosted-frame simulations, particle collisions, and mesh refinement.
  homepage: https://blast-warpx.github.io
  repository: https://github.com/BLAST-WarpX/warpx
  documentation: https://warpx.readthedocs.io

extra:
  recipe-maintainers:
    - ax3l
    - EZoni
    - RemiLehe
